#!/usr/bin/env bash

# POSTGRESQL
POSTGRES_USER=user
POSTGRES_PASSWORD=itsasecret
POSTGRES_DATABASE_DENDRITE=dendrite
POSTGRES_DATABASE_SYNC=synv3

# SYNC
SYNC_PORT=8009
SYNC_DOMAIN="matrix-sync.dionisis.xyz"

# DENDRITE
DENDRITE_CLIENT_PORT=8008
DENDRITE_CLIENT_DOMAIN="matrix.dionisis.xyz"
DENDRITE_SERVER_PORT=8448
DENDRITE_SERVER_DOMAIN="matrix-dendrite.dionisis.xyz"
